This is an implementation of the Linear Regression Model using the scikit-learn module.
The model is has an approximate efficiency of 40% which is not enough.
More refinements need to be made.

In [73]:
# Loeading the required libraries
# Modules used : Pandas, Scikit-Learn, Numpy
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [74]:
# Loading the training data set
df = pd.read_csv("bpp_training_data.csv")
df # overview of the data set

SalesID  SalePrice  MachineID  ModelID  datasource  auctioneerID  \
0       1646770     9500.0    1126363     8434         132            17   
1       1821514    14000.0    1194089    10150         132            31   
2       1505138    50000.0    1473654     4139         132            31   
3       1671174    16000.0    1327630     8591         132            31   
4       1329056    22000.0    1336053     4089         132            31   
...         ...        ...        ...      ...         ...           ...   
299995  2192279    16500.0    1701366     6272         136            78   
299996  2192338    17000.0    1787662    12919         136            78   
299997  2433168    11500.0    1714162     9580         136            78   
299998  1586638    32000.0    1386512    11398         132            78   
299999  2396198    47500.0    1082033     2144         136            78   

        YearMade  MachineHoursCurrentMeter  UsageBand  fiModelDesc  ...  \
0           1974                        17          0         4593  ...   
1           1980                        31          0         1820  ...   
2           1978                        31          0         2348  ...   
3           1980                        31          0         1819  ...   
4           1984                        31          0         2119  ...   
...          ...                       ...        ...          ...  ...   
299995      1000                        78          0         4215  ...   
299996      1000                        78          0         4216  ...   
299997      2005                        78          0         4514  ...   
299998      2005                        78          3         1202  ...   
299999      2005                        78          3         4378  ...   

        Grouser_Type  Backhoe_Mounting  Blade_Type  Travel_Controls  \
0                  0                 1           8                6   
1                  0                 0           0                0   
2                  0                 1           8                6   
3                  0                 0           0                0   
4                  0                 1           6                5   
...              ...               ...         ...              ...   
299995             0                 0           0                0   
299996             0                 0           0                0   
299997             0                 0           0                0   
299998             0                 1           6                6   
299999             1                 0           0                0   

        Differential_Type  Steering_Controls  saleYear  saleMonth  saleDay  \
0                       0                  0      1989          1       17   
1                       4                  2      1989          1       31   
2                       0                  0      1989          1       31   
3                       4                  2      1989          1       31   
4                       0                  0      1989          1       31   
...                   ...                ...       ...        ...      ...   
299995                  0                  0      2009          3       19   
299996                  0                  0      2009          3       19   
299997                  0                  0      2009          3       19   
299998                  0                  0      2009          3       19   
299999                  0                  0      2009          3       19   

        saleDayOfYear  
0                  17  
1                  31  
2                  31  
3                  31  
4                  31  
...               ...  
299995             78  
299996             78  
299997             78  
299998             78  
299999             78  

[300000 rows x 56 columns]

In [75]:
# Removing potentially unwanted features
del df['SalesID']
del df['MachineID']
del df['ModelID']
del df['datasource']
del df['auctioneerID']
df

SalePrice  YearMade  MachineHoursCurrentMeter  UsageBand  fiModelDesc  \
0          9500.0      1974                        17          0         4593   
1         14000.0      1980                        31          0         1820   
2         50000.0      1978                        31          0         2348   
3         16000.0      1980                        31          0         1819   
4         22000.0      1984                        31          0         2119   
...           ...       ...                       ...        ...          ...   
299995    16500.0      1000                        78          0         4215   
299996    17000.0      1000                        78          0         4216   
299997    11500.0      2005                        78          0         4514   
299998    32000.0      2005                        78          3         1202   
299999    47500.0      2005                        78          3         4378   

        fiBaseModel  fiSecondaryDesc  fiModelSeries  fiModelDescriptor  \
0              1744                0              0                  0   
1               559                0              0                  0   
2               713               59              0                  0   
3               558                0              0                  0   
4               683               21              0                  0   
...             ...              ...            ...                ...   
299995         1500                0              0                  0   
299996         1501                0              0                  0   
299997         1684                0              0                  0   
299998          354               75              0                  0   
299999         1594                0              0                 65   

        ProductSize  ...  Grouser_Type  Backhoe_Mounting  Blade_Type  \
0                 4  ...             0                 1           8   
1                 0  ...             0                 0           0   
2                 2  ...             0                 1           8   
3                 0  ...             0                 0           0   
4                 0  ...             0                 1           6   
...             ...  ...           ...               ...         ...   
299995            0  ...             0                 0           0   
299996            0  ...             0                 0           0   
299997            0  ...             0                 0           0   
299998            0  ...             0                 1           6   
299999            3  ...             1                 0           0   

        Travel_Controls  Differential_Type  Steering_Controls  saleYear  \
0                     6                  0                  0      1989   
1                     0                  4                  2      1989   
2                     6                  0                  0      1989   
3                     0                  4                  2      1989   
4                     5                  0                  0      1989   
...                 ...                ...                ...       ...   
299995                0                  0                  0      2009   
299996                0                  0                  0      2009   
299997                0                  0                  0      2009   
299998                6                  0                  0      2009   
299999                0                  0                  0      2009   

        saleMonth  saleDay  saleDayOfYear  
0               1       17             17  
1               1       31             31  
2               1       31             31  
3               1       31             31  
4               1       31             31  
...           ...      ...            ...  
299995          3       19             78  
299996          3       19  

In [76]:
# Creating a new DataFrame with only the target variable
df_y = df[['SalePrice']]

# Deleting the target variable column from the original DataFrame
del df['SalePrice']


In [77]:
# Creating a linear regression object
reg = linear_model.LinearRegression()

In [78]:
# Splitting 20% of the Data into test set. Will be used later to evaluate the model
x_train, x_test, y_train, y_test = train_test_split(df, df_y, test_size=0.2, random_state=4)

In [79]:
# Fitting the linear model to the training data
reg.fit(x_train, y_train)

LinearRegression()

In [80]:
# The coefficients of the Linear Regression hypothesis function
reg.coef_

array([[ 1.11332314e+01, -3.09582075e+13,  2.43810577e+03,
        -4.17339493e+00,  1.01151626e+01,  9.51505742e+01,
         7.75423117e+01,  1.37400756e+02,  1.33718581e+03,
         5.06497325e-01, -2.08142933e+01,  1.22302346e+11,
        -1.22302338e+11, -2.69545008e+03, -2.80964364e+02,
         2.71970625e+03,  2.55337000e+03,  1.41006400e+04,
        -9.46316532e+02,  1.06873389e+03, -8.34768493e+02,
         1.00163165e+04,  1.02596811e+03, -1.69244219e+04,
         3.16657780e+04,  2.72731858e+02,  1.84898836e+04,
         2.03253739e+03,  7.33736023e+03,  2.22109894e+03,
        -1.37944036e+02, -3.62400920e+03, -1.80645805e+03,
         1.69687941e+03,  1.51401956e+03,  1.65963665e+04,
        -4.25413886e+01, -7.50289332e+02, -3.10811688e+03,
         5.99871577e+03,  5.33394858e+02,  2.45004180e+04,
         1.74830543e+03, -8.26160907e+03, -2.18128995e+03,
        -6.80218652e+03, -1.81375126e+02, -7.45191028e+02,
        -3.30011196e+01,  3.09582075e+13]])

In [81]:
# Intercept of the Linear Regression Hypothesis function
reg.intercept_

array([334489.80384583])

In [82]:
# Making predictions over the test set
a = reg.predict(x_test)
a

array([[11508.80384583],
       [14967.80384583],
       [59610.55384583],
       ...,
       [38895.80384583],
       [ 9933.80384583],
       [19716.80384583]])

In [89]:
# Calculating the mean square error
print(np.mean((a - y_test)**2))

SalePrice    3.144334e+08
dtype: float64


In [84]:
# Evaluating our model on the test set to know its approximate efficiency
reg.score(x_test, y_test)

0.40600263558032945